In [19]:
# Using Python List
import numpy as np
import time

size = 100_000_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x + y for x, y in zip(l1, l2)]
end = time.time()

print(add[0: 10])
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.5770008563995361


In [2]:
# Using Numpy Arrays

import numpy as np
import time

size = 10_000_000
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()

print(add)
print(end-start)

[        0         2         4 ... 199999994 199999996 199999998]
0.33072948455810547


In [3]:
# Python Zip Expalined
lis1 = [1, 2, 3]
lis2 = [4, 5, 6]


list(zip(lis1, lis2))

[(1, 4), (2, 5), (3, 6)]

In [4]:
# 1D array
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [5]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(2, 3)

In [8]:
# Squaring usingpython list
start_time = time.time()
list_square = [x**2 for x in range(100_000_000)]
end_time = time.time()

print(list_square[0: 10])
print(end_time-start_time)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
7.922995090484619


In [9]:
# Squaring using numpy
start_time = time.time()
arr = np.arange(100_000_000)
list_square = arr**2
end_time = time.time()

print(list_square[0: 10])
print(end_time-start_time)

[ 0  1  4  9 16 25 36 49 64 81]
1.2863295078277588
