In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.full((3, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.eye(3)      # same as identity function

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(1, 100, 4)      # From 1 to (100 - 4), with difference 4

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [9]:
np.linspace(1, 100, 5)        # From 1 to 100, divided into 5 parts where difference is same.

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [10]:
myArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
myArr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
myArr.shape

(4, 3)

In [12]:
myArr.size     # Total number of elements (4 x 3)

12

In [13]:
myArr.ndim

2

In [14]:
myArr.dtype

dtype('int32')

In [15]:
myArrFloat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype='float32')
myArrFloat

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [16]:
n = myArrFloat.astype('float64')

In [17]:
n.dtype

dtype('float64')

In [18]:
myArr.shape

(4, 3)

In [19]:
reshapred = myArr.reshape(6, 2)
print(myArr)
print(reshapred)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [20]:
reshapred.shape

(6, 2)

In [21]:
myArr.flatten()       # Will convert the array in 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])