In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
flat[0]

1

In [5]:
flat[5]

6

In [6]:
flat[3:6]

array([4, 5, 6])

In [7]:
flat[:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[4:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
flat[::2]       # Every second (2nd) element

array([ 1,  3,  5,  7,  9, 11])

In [10]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
b = flat[3: 7]

In [12]:
b

array([4, 5, 6, 7])

In [13]:
b[0]

4

In [14]:
b[0] = 4444

In [15]:
b

array([4444,    5,    6,    7])

In [16]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [17]:
c = flat[0:5].copy()

In [18]:
c

array([   1,    2,    3, 4444,    5])

In [19]:
c[0] = 333

In [20]:
c

array([ 333,    2,    3, 4444,    5])

In [21]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [22]:
arr = np.array([1, 43, 45, 34, 67, 28, 12])

In [23]:
# Fancy Indexing

arr[[1, 4, 5]]     # Will return the elements of these index

array([43, 67, 28])

In [24]:
# Boolean Masking

arr[arr > 3]        # Will return the elements that are greater than 3

array([43, 45, 34, 67, 28, 12])

In [25]:
newArr = np.random.randint(0, 10, size=(3, 3))
newArr

array([[6, 1, 8],
       [2, 0, 1],
       [6, 9, 2]])

In [26]:
newArr.shape

(3, 3)

In [27]:
floarArr = np.array([1.1, 2.2, 3.3], dtype='int32')
floarArr

array([1, 2, 3])

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[arr % 2 == 0]

array([2, 4, 6])

In [29]:
demo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
demo.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
boolFind = np.random.randint(1, 100, size=(1, 50))
boolFind

array([[95, 16, 71,  9, 66, 38, 10, 82, 70, 86, 55, 66, 13, 98, 89, 83,
        24,  1,  5, 23, 50, 39,  4, 29, 13, 87, 40,  3, 15,  4, 74,  4,
        68, 98, 60, 58, 61, 65, 68, 11, 80, 65, 29,  4,  8, 50, 79, 96,
        33, 88]])

In [32]:
boolFind[boolFind > 50]            # Using Boolean Masking

array([95, 71, 66, 82, 70, 86, 55, 66, 98, 89, 83, 87, 74, 68, 98, 60, 58,
       61, 65, 68, 80, 65, 79, 96, 88])