In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
flat[0]

1

In [5]:
flat[5]

6

In [6]:
flat[3:6]

array([4, 5, 6])

In [7]:
flat[:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[4:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
flat[::2]       # Every second (2nd) element

array([ 1,  3,  5,  7,  9, 11])

In [20]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
b = flat[3: 7]

In [24]:
b

array([4, 5, 6, 7])

In [26]:
b[0]

4

In [28]:
b[0] = 4444

In [30]:
b

array([4444,    5,    6,    7])

In [32]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [34]:
c = flat[0:5].copy()

In [36]:
c

array([   1,    2,    3, 4444,    5])

In [38]:
c[0] = 333

In [40]:
c

array([ 333,    2,    3, 4444,    5])

In [42]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [46]:
arr = np.array([1, 43, 45, 34, 67, 28, 12])

In [52]:
# Fancy Indexing

arr[[1, 4, 5]]     # Will return the elements of these index

array([43, 67, 28])

In [54]:
# Boolean Masking

arr[arr > 3]        # Will return the elements that are greater than 3

array([43, 45, 34, 67, 28, 12])

In [94]:
newArr = np.random.randint(0, 10, size=(3, 3))
newArr

array([[6, 5, 7],
       [6, 7, 6],
       [1, 7, 2]])

In [96]:
newArr.shape

(3, 3)

In [100]:
floarArr = np.array([1.1, 2.2, 3.3], dtype='int32')
floarArr

array([1, 2, 3])

In [110]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[arr % 2 == 0]

array([2, 4, 6])

In [112]:
demo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
demo.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
boolFind = np.random.randint(1, 100, size=(1, 50))
boolFind

array([[47, 68, 17, 62, 29, 17, 37, 38, 38, 70, 75, 76, 85, 30, 32, 45,
        92, 49, 55, 72, 93, 70, 37, 23, 51, 33, 74, 37, 97, 84, 81, 93,
        89, 34, 43, 35,  5, 69, 77, 69, 17, 71, 74, 56, 24, 46,  5, 86,
        60, 79]])